version: 2.1
orbs:
  ci-go: ipfs/ci-go@0.1.5

workflows:
  version: 2
  test:
    jobs:
      - ci-go/build
      - ci-go/lint
      - ci-go/test
      - ci-go/benchmark:
          tolerance: 25
          requires:
            - ci-go/test
