version: 2.1
orbs:
  ci-go: ipfs/ci-go@0.1.9

executors:
  macos:
    macos:
      xcode: "10.0.0"
    environment:
      GIT_PAGER: cat
      GO111MODULE: "on"
      GOPATH: /go
      GOCACHE: /go/cache
      PATH: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/local/go/bin:/go/bin
      IPFS_DISTS: https://dist.ipfs.io

commands:
  configure-macos:
    parameters:
      version:
        type: string
        default: 1.12.7
      testsum-version:
        type: string
        default: v0.3.5
    steps:
      - run:
          name: "Making the go workspace"
          command: |
            sudo mkdir /go
            sudo chmod 1777 /go
      - restore_cache:
          name: "Restoring Go Compiler"
          keys:
            - v2-gocc-<< parameters.version>>-{{ arch }}
      - run:
          name: "Installing go"
          command: |
            if [ ! -e /private/tmp/gocc-cache/gocc.tar.gz ]; then
              case "$(uname -m)" in
                x86_64) ARCH=amd64 ;;
                i386) ARCH=386 ;;
                *) exit 1 ;;
              esac
              mkdir /private/tmp/gocc-cache/
              curl -sSL -o /private/tmp/gocc-cache/gocc.tar.gz "https://dl.google.com/go/go<< parameters.version >>.darwin-$ARCH.tar.gz"
            fi
            sudo tar -xz -f /private/tmp/gocc-cache/gocc.tar.gz -C /usr/local/
      - save_cache:
          name: "Caching Go Compiler"
          key: v2-gocc-<< parameters.version>>-{{ arch }}
          paths:
            - /private/tmp/gocc-cache
      - restore_cache:
          name: "Restoring Tools"
          keys:
            - v1-gotools-{{ arch }}-testsum@<< parameters.testsum-version >>:go@<< parameters.version >>
      - run:
          name: "Installing Tools"
          command: |
            which gotestsum >/dev/null 2>&1 || go get gotest.tools/gotestsum@v0.3.5
            # Finally, clean out the gopath so we don't sully the cache.
            sudo rm -rf /go/cache /go/pkg /go/src
      - save_cache:
          name: "Caching Tools"
          key: v1-gotools-{{ arch }}-testsum@<< parameters.testsum-version >>:go@<< parameters.version >>
          paths:
            /go/bin

workflows:
  version: 2
  test:
    jobs:
      - ci-go/build
      - ci-go/lint
      - ci-go/test
      - ci-go/test:
          name: ci-go/test/macos
          executor: macos
          pre-steps:
            - configure-macos
      - ci-go/benchmark:
          tolerance: 50
          requires:
            - ci-go/test
